### ISSUE TITLE
system-id is restricted in length

### ISSUE THREAD

**Issue by dshcherb** [greenpau/ovsdb#3]
The length of the system-id field is limited to 36 (32 per the log message) bytes:
https://github.com/greenpau/ovsdb/blob/cc0e61b9c81c89b7333fff4b53b7256ed29f926e/system.go#L82-L84

Which results in errors in the software using this client library such as the ovs_exporter when system-id is longer:

```
Aug 23 09:38:59 juju-c2e20a-zaza-14f217809f05-8 prometheus-ovs-exporter.ovs-exporter[639725]: time="2022-08-23T09:38:59Z" level=error msg="Open_vSwitch: system-id is not 32 characters in length, but 51" source="ovs_exporter.go:477"
```

**Expected behavior**

The length of the system-id field should not be limited as it is done currently. OVS does not document any specific limit of system-id:

https://github.com/openvswitch/ovs/blob/ff55e8f3858ae153ef1996df3d52938f3df6d950/vswitchd/vswitch.xml#L70-L73

https://github.com/openvswitch/ovs/blob/ff55e8f3858ae153ef1996df3d52938f3df6d950/vswitchd/vswitch.ovsschema#L27-L29
```
       "external_ids": {
         "type": {"key": "string", "value": "string",
                  "min": 0, "max": "unlimited"}},
```

The system-id itself could also be taken from ovsdb instead of being taken from a file in distribution-specific filesystem location as it is done now.

**Example**

OpenVSwitch is able to accept system-ids longer than the 32-byte limit (in this case it's 51):

```
sudo ovs-vsctl get open . external-ids
{hostname=juju-c2e20a-zaza-14f217809f05-8.project.serverstack, ovn-encap-ip="10.5.1.206", ovn-encap-type=geneve, ovn-match-northd-version="true", ovn-remote="ssl:10.5.0.181:6642,ssl:10.5.0.206:6642,ssl:10.5.1.35:6642", rundir="/var/run/openvswitch", system-id=juju-c2e20a-zaza-14f217809f05-8.project.serverstack}
```

So the library could just rely on OVS to validate the system-id if it ever needs to do so.

**Comment by greenpau** [comment]
Resolved.
